### ISSUE TITLE
Weight File 

### ISSUE THREAD

**Issue by Gaurav14cs17** [INDTLab/PMTSPN#1]
It's amazing paper ... Results is gud ... thanks Author for such good paper and result..

But weight file is missing ?

**Comment by weibo21** [comment]
Thanks for the reminder. We now provide the weight file in the following link, https://pan.baidu.com/s/1-clCXW2L-1aS6AamSb3pQQ, and the code is  4jd9. For the predicted data, you can find it at index 29 in "all_outputs.pt", and the training logs are in "readme.txt". Unfortunately, the weight file for the 29th round got overwritten during training. But don't worry, you can try our other results, which might perform even better according to the training logs. You can also reproduce our results since we offer the training code. 

Just a tip: If you want to load the weights, check the settings (Specifically, the name of the network.) in the training logs.

**Comment by Gaurav14cs17** [comment]
Thanku so much @weibo21 ... I am unable to download to this weight file from Baidu ...could you send me on email : gourav14cs17@gmail.com

**Comment by weibo21** [comment]
Alright, now we're providing a Google Drive link (see https://drive.google.com/file/d/1ixW7l4HMrvcSg6KOadQwD--VMBdegL3c/view?usp=sharing) to make it convenient for readers from different regions. Thank you for your interest.

**Comment by Gaurav14cs17** [comment]
@weibo21 thanku so much

**Comment by Gaurav14cs17** [comment]
Thanku
